GRIP=grip
FLAGS=--export

pages:
	$(GRIP) $(FLAGS) --title='Access' access.md
	$(GRIP) $(FLAGS) --title='Compiling' compiling.md
	$(GRIP) $(FLAGS) --title='Control' control.md
	$(GRIP) $(FLAGS) --title='Variables' decl.md
	$(GRIP) $(FLAGS) --title='Exceptions' exceptions.md
	$(GRIP) $(FLAGS) --title='Lambda Functions' lambda.md
	$(GRIP) $(FLAGS) --title='Null' null.md
	$(GRIP) $(FLAGS) --title='OOP' oop.md
	$(GRIP) $(FLAGS) --title='Short Circuiting' short.md
	$(GRIP) $(FLAGS) --title='Static' static.md
	$(GRIP) $(FLAGS) --title='Super' super.md
	$(GRIP) $(FLAGS) --title='Generics' generics.md
	$(GRIP) $(FLAGS) --title='Testing' testing.md
	$(GRIP) $(FLAGS) --title='Types' types.md

clean:
	rm -f access.html compiling.html control.html decl.html exceptions.html lambda.html null.html oop.html short.html static.html super.html generics.html testing.html types.html
